import { FRIEND_GENDER } from "./friend";
import type { CatalogItem, ColorId, GenderId, ItemCategory, LookTemplate, StyleCard } from "./types";

/**
 * Legacy closet / elevate stills only.
 * Generate and stylist packets use `data/mvp-catalog.json` via `mvp-catalog.ts`.
 */
export const CATALOG: CatalogItem[] = [
  {
    id: "sh-navy-oxford",
    name: { en: "Navy oxford shirt", pt: "Camisa oxford navy" },
    category: "shirt",
    priceEur: 39.9,
    color: "navy",
    vibeTags: ["work", "smart-casual", "weekend"],
  },
  {
    id: "sh-white-poplin",
    name: { en: "White poplin shirt", pt: "Camisa poplin branca" },
    category: "shirt",
    priceEur: 29.9,
    color: "white",
    vibeTags: ["work", "date", "evening", "travel"],
  },
  {
    id: "sh-stone-linen",
    name: { en: "Stone linen shirt", pt: "Camisa de linho stone" },
    category: "shirt",
    priceEur: 45.9,
    color: "stone",
    vibeTags: ["weekend", "travel", "date"],
  },
  {
    id: "sh-sand-camp",
    name: { en: "Sand camp-collar shirt", pt: "Camisa camp sand" },
    category: "shirt",
    priceEur: 35.9,
    color: "sand",
    vibeTags: ["weekend", "travel"],
  },
  {
    id: "sh-charcoal-twill",
    name: { en: "Charcoal twill shirt", pt: "Camisa twill carvão" },
    category: "shirt",
    priceEur: 39.9,
    color: "charcoal",
    vibeTags: ["work", "evening"],
  },
  {
    id: "sh-cream-oxford",
    name: { en: "Cream oxford shirt", pt: "Camisa oxford creme" },
    category: "shirt",
    priceEur: 35.9,
    color: "cream",
    vibeTags: ["weekend", "smart-casual", "date"],
  },
  {
    id: "sh-black-silk",
    name: { en: "Black silk-touch shirt", pt: "Camisa preta toque seda" },
    category: "shirt",
    priceEur: 49.9,
    color: "black",
    vibeTags: ["evening", "date", "work"],
  },
  {
    id: "kn-grey-merino",
    name: { en: "Grey merino crew", pt: "Camisola merino cinza" },
    category: "knit",
    priceEur: 49.9,
    color: "grey",
    vibeTags: ["weekend", "work", "smart-casual"],
  },
  {
    id: "kn-ivory-roll",
    name: { en: "Ivory roll-neck", pt: "Gola alta marfim" },
    category: "knit",
    priceEur: 45.9,
    color: "cream",
    vibeTags: ["weekend", "date", "smart-casual"],
  },
  {
    id: "kn-navy-halfzip",
    name: { en: "Navy half-zip knit", pt: "Malha navy meio fecho" },
    category: "knit",
    priceEur: 55.9,
    color: "navy",
    vibeTags: ["travel", "work", "weekend"],
  },
  {
    id: "kn-black-turtleneck",
    name: { en: "Black merino turtleneck", pt: "Gola alta merino preta" },
    category: "knit",
    priceEur: 59.9,
    color: "black",
    vibeTags: ["evening", "date", "work"],
  },
  {
    id: "kn-camel-polo",
    name: { en: "Camel knit polo", pt: "Pólo de malha camel" },
    category: "knit",
    priceEur: 39.9,
    color: "camel",
    vibeTags: ["weekend", "smart-casual", "date"],
  },
  {
    id: "kn-chocolate-crew",
    name: { en: "Chocolate cotton crew", pt: "Camisola chocolate" },
    category: "knit",
    priceEur: 42.9,
    color: "chocolate",
    vibeTags: ["date", "weekend", "evening"],
  },
  {
    id: "kn-taupe-cardigan",
    name: { en: "Taupe fine cardigan", pt: "Cardigan taupe fino" },
    category: "knit",
    priceEur: 49.9,
    color: "stone",
    vibeTags: ["smart-casual", "work", "weekend"],
  },
  {
    id: "te-navy-polo",
    name: { en: "Navy piqué polo", pt: "Pólo piqué navy" },
    category: "tee",
    priceEur: 25.9,
    color: "navy",
    vibeTags: ["weekend", "travel", "smart-casual"],
  },
  {
    id: "te-white-heavy",
    name: { en: "Heavy white tee", pt: "T-shirt branca pesada" },
    category: "tee",
    priceEur: 19.9,
    color: "white",
    vibeTags: ["weekend", "travel", "smart-casual"],
  },
  {
    id: "te-black-box",
    name: { en: "Black boxy tee", pt: "T-shirt boxy preta" },
    category: "tee",
    priceEur: 19.9,
    color: "black",
    vibeTags: ["smart-casual", "weekend", "evening"],
  },
  {
    id: "te-olive-henley",
    name: { en: "Olive henley", pt: "Henley olive" },
    category: "tee",
    priceEur: 22.9,
    color: "olive",
    vibeTags: ["travel", "weekend"],
  },
  {
    id: "te-sand-polo",
    name: { en: "Sand linen-blend polo", pt: "Pólo linho sand" },
    category: "tee",
    priceEur: 29.9,
    color: "sand",
    vibeTags: ["weekend", "travel", "date"],
  },
  {
    id: "te-grey-long",
    name: { en: "Grey long-sleeve tee", pt: "T-shirt manga comprida cinza" },
    category: "tee",
    priceEur: 22.9,
    color: "grey",
    vibeTags: ["weekend", "smart-casual"],
  },
  {
    id: "tr-navy-chino",
    name: { en: "Navy tapered chinos", pt: "Chinos navy afilados" },
    category: "trousers",
    priceEur: 49.9,
    color: "navy",
    vibeTags: ["work", "smart-casual", "travel"],
  },
  {
    id: "tr-stone-chino",
    name: { en: "Stone chinos", pt: "Chinos stone" },
    category: "trousers",
    priceEur: 45.9,
    color: "stone",
    vibeTags: ["weekend", "work", "travel"],
  },
  {
    id: "tr-black-wool",
    name: { en: "Black wool trousers", pt: "Calças de lã pretas" },
    category: "trousers",
    priceEur: 69.9,
    color: "black",
    vibeTags: ["work", "evening", "date"],
  },
  {
    id: "tr-grey-flannel",
    name: { en: "Grey flannel trousers", pt: "Calças flanela cinza" },
    category: "trousers",
    priceEur: 59.9,
    color: "grey",
    vibeTags: ["work", "smart-casual", "evening"],
  },
  {
    id: "tr-charcoal-pleat",
    name: { en: "Charcoal pleated trousers", pt: "Calças pregas carvão" },
    category: "trousers",
    priceEur: 59.9,
    color: "charcoal",
    vibeTags: ["work", "evening"],
  },
  {
    id: "tr-sand-linen",
    name: { en: "Sand linen trousers", pt: "Calças de linho sand" },
    category: "trousers",
    priceEur: 49.9,
    color: "sand",
    vibeTags: ["weekend", "travel", "date"],
  },
  {
    id: "tr-olive-utility",
    name: { en: "Olive utility trousers", pt: "Calças utility olive" },
    category: "trousers",
    priceEur: 49.9,
    color: "olive",
    vibeTags: ["travel", "weekend", "smart-casual"],
  },
  {
    id: "tr-cream-wide",
    name: { en: "Cream wide trousers", pt: "Calças largas creme" },
    category: "trousers",
    priceEur: 55.9,
    color: "cream",
    vibeTags: ["date", "weekend", "smart-casual"],
  },
  {
    id: "tr-chocolate-twill",
    name: { en: "Chocolate twill trousers", pt: "Calças twill chocolate" },
    category: "trousers",
    priceEur: 49.9,
    color: "chocolate",
    vibeTags: ["date", "evening", "weekend"],
  },
  {
    id: "tr-indigo-selvedge",
    name: { en: "Indigo slim jeans", pt: "Jeans slim indigo" },
    category: "trousers",
    priceEur: 45.9,
    color: "navy",
    vibeTags: ["weekend", "smart-casual"],
  },
  {
    id: "so-stone-linen",
    name: { en: "Stone linen shorts", pt: "Calções de linho stone" },
    category: "shorts",
    priceEur: 35.9,
    color: "stone",
    vibeTags: ["weekend", "travel"],
  },
  {
    id: "so-navy-tailored",
    name: { en: "Navy tailored shorts", pt: "Calções alfaiataria navy" },
    category: "shorts",
    priceEur: 39.9,
    color: "navy",
    vibeTags: ["weekend", "travel", "smart-casual"],
  },
  {
    id: "so-sand-draw",
    name: { en: "Sand drawstring shorts", pt: "Calções sand cordão" },
    category: "shorts",
    priceEur: 29.9,
    color: "sand",
    vibeTags: ["weekend", "travel"],
  },
  {
    id: "ow-camel-overcoat",
    name: { en: "Camel overcoat", pt: "Sobretudo camel" },
    category: "outerwear",
    priceEur: 129.9,
    color: "camel",
    vibeTags: ["work", "evening", "date"],
  },
  {
    id: "ow-navy-blazer",
    name: { en: "Navy unstructured blazer", pt: "Blazer navy sem estrutura" },
    category: "outerwear",
    priceEur: 89.9,
    color: "navy",
    vibeTags: ["work", "smart-casual", "evening"],
  },
  {
    id: "ow-black-bomber",
    name: { en: "Black technical bomber", pt: "Bomber técnico preto" },
    category: "outerwear",
    priceEur: 69.9,
    color: "black",
    vibeTags: ["smart-casual", "weekend", "evening"],
  },
  {
    id: "ow-olive-field",
    name: { en: "Olive field jacket", pt: "Casaco field olive" },
    category: "outerwear",
    priceEur: 79.9,
    color: "olive",
    vibeTags: ["travel", "weekend"],
  },
  {
    id: "ow-grey-mac",
    name: { en: "Grey compact mac", pt: "Gabardine cinza compacta" },
    category: "outerwear",
    priceEur: 89.9,
    color: "grey",
    vibeTags: ["travel", "work", "weekend"],
  },
  {
    id: "ow-black-coat",
    name: { en: "Black wool coat", pt: "Casaco de lã preto" },
    category: "outerwear",
    priceEur: 119.9,
    color: "black",
    vibeTags: ["work", "evening", "date"],
  },
  {
    id: "ow-stone-overshirt",
    name: { en: "Stone overshirt", pt: "Overshirt stone" },
    category: "outerwear",
    priceEur: 59.9,
    color: "stone",
    vibeTags: ["weekend", "travel", "smart-casual"],
  },
  {
    id: "ow-charcoal-suit",
    name: { en: "Charcoal soft jacket", pt: "Casaco mole carvão" },
    category: "outerwear",
    priceEur: 99.9,
    color: "charcoal",
    vibeTags: ["work", "evening"],
  },
  {
    id: "sh-navy-derby",
    name: { en: "Navy suede derby", pt: "Derby camurça navy" },
    category: "shoes",
    priceEur: 79.9,
    color: "navy",
    vibeTags: ["work", "smart-casual"],
  },
  {
    id: "sh-black-oxford",
    name: { en: "Black leather oxford", pt: "Oxford de pele preto" },
    category: "shoes",
    priceEur: 89.9,
    color: "black",
    vibeTags: ["work", "evening", "date"],
  },
  {
    id: "sh-white-court",
    name: { en: "White court sneaker", pt: "Sneaker court branco" },
    category: "shoes",
    priceEur: 49.9,
    color: "white",
    vibeTags: ["weekend", "travel", "smart-casual"],
  },
  {
    id: "sh-stone-loafer",
    name: { en: "Stone suede loafer", pt: "Mocassim camurça stone" },
    category: "shoes",
    priceEur: 69.9,
    color: "stone",
    vibeTags: ["weekend", "date", "smart-casual"],
  },
  {
    id: "sh-chocolate-chelsea",
    name: { en: "Chocolate chelsea boot", pt: "Chelsea chocolate" },
    category: "shoes",
    priceEur: 89.9,
    color: "chocolate",
    vibeTags: ["date", "evening", "work"],
  },
  {
    id: "sh-sand-espadrille",
    name: { en: "Sand canvas espadrille", pt: "Alpargata sand" },
    category: "shoes",
    priceEur: 29.9,
    color: "sand",
    vibeTags: ["weekend", "travel"],
  },
  {
    id: "sh-grey-runner",
    name: { en: "Grey city runner", pt: "Runner cinza cidade" },
    category: "shoes",
    priceEur: 59.9,
    color: "grey",
    vibeTags: ["travel", "weekend", "smart-casual"],
  },
  {
    id: "sh-olive-chukka",
    name: { en: "Olive suede chukka", pt: "Chukka camurça olive" },
    category: "shoes",
    priceEur: 79.9,
    color: "olive",
    vibeTags: ["travel", "weekend"],
  },
  {
    id: "sh-camel-loafer",
    name: { en: "Camel penny loafer", pt: "Mocassim camel" },
    category: "shoes",
    priceEur: 69.9,
    color: "camel",
    vibeTags: ["work", "date", "smart-casual"],
  },
  {
    id: "ac-black-belt",
    name: { en: "Black leather belt", pt: "Cinto de pele preto" },
    category: "accessory",
    priceEur: 25.9,
    color: "black",
    vibeTags: ["work", "evening", "date", "smart-casual"],
  },
  {
    id: "ac-navy-scarf",
    name: { en: "Navy merino scarf", pt: "Cachecol merino navy" },
    category: "accessory",
    priceEur: 29.9,
    color: "navy",
    vibeTags: ["work", "travel", "weekend"],
  },
  {
    id: "ac-cream-cap",
    name: { en: "Cream wool cap", pt: "Boné de lã creme" },
    category: "accessory",
    priceEur: 19.9,
    color: "cream",
    vibeTags: ["weekend", "smart-casual"],
  },
  {
    id: "ac-chocolate-belt",
    name: { en: "Chocolate suede belt", pt: "Cinto camurça chocolate" },
    category: "accessory",
    priceEur: 22.9,
    color: "chocolate",
    vibeTags: ["date", "weekend", "evening"],
  },
  {
    id: "ac-stone-tote",
    name: { en: "Stone canvas tote", pt: "Tote canvas stone" },
    category: "accessory",
    priceEur: 35.9,
    color: "stone",
    vibeTags: ["travel", "weekend", "work"],
  },
  {
    id: "ac-black-cardholder",
    name: { en: "Black cardholder", pt: "Porta-cartões preto" },
    category: "accessory",
    priceEur: 19.9,
    color: "black",
    vibeTags: ["work", "evening", "date"],
  },
  {
    id: "ow-navy-coat",
    name: { en: "Navy wool coat", pt: "Casaco de lã navy" },
    category: "outerwear",
    priceEur: 98,
    color: "navy",
    vibeTags: ["work", "weekend", "smart-casual"],
  },
  {
    id: "kn-cream-crew",
    name: { en: "Cream knit", pt: "Malha creme" },
    category: "knit",
    priceEur: 72,
    color: "cream",
    vibeTags: ["weekend", "smart-casual", "work"],
  },
  {
    id: "sh-leather-loafer",
    name: { en: "Leather loafers", pt: "Mocassins de pele" },
    category: "shoes",
    priceEur: 88,
    color: "chocolate",
    vibeTags: ["work", "weekend", "smart-casual", "date"],
  },
];

function photo(id: string, w = 900, h = 1200): string {
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`;
}

const HOUSE_BRAND: Record<ItemCategory, string> = {
  outerwear: "Northgate",
  knit: "Vale Knit",
  shirt: "Harbor Lane",
  tee: "Atelier Studio",
  trousers: "Field Notes",
  shorts: "Sunday Cut",
  shoes: "Tarnish",
  accessory: "Ink Room",
};

/** Rights-safe Unsplash product stills — not retailer or Instagram assets. */
const PRODUCT_STILL: Record<ItemCategory, string> = {
  outerwear: "photo-1551028719-00167b16eac5",
  knit: "photo-1434389677669-e08b4cac3105",
  shirt: "photo-1603252109303-2751441dd157",
  tee: "photo-1523381210434-271e8be1f52b",
  trousers: "photo-1624378439575-d8705ad7ae80",
  shorts: "photo-1591195853828-11db59a44f6b",
  shoes: "photo-1549298916-b41d501d3772",
  accessory: "photo-1584917865442-de89df76afd3",
};

export function itemBrand(item: CatalogItem): string {
  return item.brand ?? HOUSE_BRAND[item.category];
}

export function itemImage(item: CatalogItem): string {
  return item.imageUrl ?? photo(PRODUCT_STILL[item.category], 600, 600);
}

export const LOOK_TEMPLATES: LookTemplate[] = [
  {
    id: "navy-day",
    gender: "male",
    title: "Uptown Navy",
    why: "A navy coat over merino is city polish without a matching suit. Grey keeps it from looking costumed.",
    occasion: "work",
    colors: ["navy", "grey", "white"],
    imageUrl: photo("photo-1552374196-1ab2a1c593e8"),
    slots: ["outerwear", "knit", "trousers", "shoes"],
    cluster: "Uptown Navy",
    itemIds: ["ow-navy-coat", "kn-grey-merino", "tr-navy-chino", "sh-navy-derby"],
  },
  {
    id: "soft-weekend",
    gender: "male",
    title: "Harbor Knit",
    why: "Cream knit and stone trousers read like a day off that still got dressed. Soft, not sloppy.",
    occasion: "weekend",
    colors: ["cream", "stone", "white"],
    imageUrl: photo("photo-1506634572416-48cdfe530110"),
    slots: ["knit", "trousers", "shoes"],
    cluster: "Harbor Knit",
    itemIds: ["kn-cream-crew", "tr-stone-chino", "sh-stone-loafer"],
  },
  {
    id: "modern-minimal",
    gender: "male",
    title: "Ink After Dark",
    why: "Black and grey stay quiet after dark. A clean tee under structure is enough.",
    occasion: "night",
    colors: ["black", "grey", "white"],
    imageUrl: photo("photo-1519085360753-af0119f7cbe7"),
    slots: ["outerwear", "tee", "trousers", "shoes"],
    cluster: "Ink After Dark",
    itemIds: ["ow-black-bomber", "te-white-heavy", "tr-black-wool", "sh-white-court"],
  },
  {
    id: "city-ease",
    gender: "male",
    title: "Paddock Wool",
    why: "Camel overcoat, white shirt, navy underneath — quiet luxury with a little dirt on the hem.",
    occasion: "event",
    colors: ["camel", "navy", "white"],
    imageUrl: photo("photo-1490111718993-d98654ce6cf7"),
    slots: ["outerwear", "shirt", "trousers", "shoes"],
    cluster: "Paddock Wool",
    itemIds: ["ow-camel-overcoat", "sh-white-poplin", "tr-navy-chino", "sh-camel-loafer"],
  },
  {
    id: "weekend-ecru",
    gender: "male",
    title: "Sunday Linen",
    why: "Light tones open the silhouette. A camp shirt and stone trousers feel like time off on purpose.",
    occasion: "weekend",
    colors: ["cream", "sand", "stone"],
    imageUrl: photo("photo-1490578474895-699cd4e2cf59"),
    slots: ["shirt", "trousers", "shoes"],
    cluster: "Sunday Linen",
    itemIds: ["sh-sand-camp", "tr-cream-wide", "sh-sand-espadrille"],
  },
  {
    id: "charcoal-office",
    gender: "male",
    title: "Uptown Navy",
    why: "A pale shirt against charcoal is enough contrast. The belt finishes it — skip the loud accessory.",
    occasion: "work",
    colors: ["charcoal", "white", "black"],
    imageUrl: photo("photo-1507679799987-c73779587ccf"),
    slots: ["shirt", "trousers", "shoes", "accessory"],
    cluster: "Uptown Navy",
    itemIds: ["sh-white-poplin", "tr-charcoal-pleat", "sh-black-oxford", "ac-black-belt"],
  },
  {
    id: "olive-layer",
    gender: "male",
    title: "Field & Flannel",
    why: "Olive over stone is travel that still looks like a choice. Rugged, not camping.",
    occasion: "travel",
    colors: ["olive", "stone", "grey"],
    imageUrl: photo("photo-1516826957135-700dedea698c"),
    slots: ["outerwear", "tee", "trousers", "shoes"],
    cluster: "Field & Flannel",
    itemIds: ["ow-olive-field", "te-olive-henley", "tr-stone-chino", "sh-olive-chukka"],
  },
  {
    id: "night-wool",
    title: "Ink After Dark",
    why: "Black wool reads finished after dark. Keep the shirt quiet so the coat does the work.",
    occasion: "night",
    colors: ["black", "charcoal", "grey"],
    imageUrl: photo("photo-1613909671501-f9678ffc1d33"),
    slots: ["outerwear", "shirt", "trousers", "shoes"],
    cluster: "Ink After Dark",
    gender: "male",
    itemIds: ["ow-black-coat", "sh-black-silk", "tr-black-wool", "sh-black-oxford"],
  },
  {
    id: "f-camel-midi",
    gender: "female",
    title: "Paddock Cashmere",
    why: "Camel from coat to loafer is one warm column. Cream at the neck is the only break — quiet luxury with a shopping-day edge.",
    occasion: "event",
    colors: ["camel", "cream", "white"],
    imageUrl: photo("photo-1483985988355-763728e1935b"),
    slots: ["outerwear", "knit", "trousers", "shoes"],
    cluster: "Paddock Cashmere",
    itemIds: ["ow-camel-overcoat", "kn-cream-crew", "tr-cream-wide", "sh-camel-loafer"],
  },
  {
    id: "f-navy-work",
    gender: "female",
    title: "Uptown Saddle",
    why: "A tailored jacket and pale shirt is enough structure. The chino keeps it from a matching suit — city polish, riding-boot energy.",
    occasion: "work",
    colors: ["navy", "white", "grey"],
    imageUrl: photo("photo-1590873802674-55bb8f947bc5"),
    slots: ["outerwear", "shirt", "trousers", "shoes"],
    cluster: "Uptown Saddle",
    itemIds: ["ow-navy-blazer", "sh-white-poplin", "tr-navy-chino", "sh-navy-derby"],
  },
  {
    id: "f-black-column",
    gender: "female",
    title: "Ink After Dark",
    why: "Evening as a single dark line. The turtleneck keeps the coat from needing jewelry.",
    occasion: "night",
    colors: ["black", "charcoal", "grey"],
    imageUrl: photo("photo-1495385794356-15371f348c31"),
    slots: ["outerwear", "knit", "trousers", "shoes"],
    cluster: "Ink After Dark",
    itemIds: ["ow-black-coat", "kn-black-turtleneck", "tr-black-wool", "sh-black-oxford"],
  },
  {
    id: "f-stone-weekend",
    gender: "female",
    title: "Harbor Granddaughter",
    why: "A taupe cardigan over a white tee is finished without trying. Salt-air ease, cream knit, nothing precious.",
    occasion: "weekend",
    colors: ["cream", "stone", "white"],
    imageUrl: photo("photo-1632765937900-a3bbbfa58d46"),
    slots: ["knit", "tee", "trousers", "shoes"],
    cluster: "Harbor Granddaughter",
    itemIds: ["kn-taupe-cardigan", "te-white-heavy", "tr-stone-chino", "sh-stone-loafer"],
  },
  {
    id: "f-olive-ease",
    gender: "female",
    title: "Harvest Tweed",
    why: "Olive over sand is travel with a moodier fall edge. Preppy, not costume.",
    occasion: "travel",
    colors: ["olive", "sand", "stone"],
    imageUrl: photo("photo-1545291730-faff8ca1d4b0"),
    slots: ["outerwear", "tee", "trousers", "shoes"],
    cluster: "Harvest Tweed",
    itemIds: ["ow-olive-field", "te-sand-polo", "tr-sand-linen", "sh-sand-espadrille"],
  },
  {
    id: "f-grey-mac",
    gender: "female",
    title: "Sunday Linen",
    why: "White cotton and sneakers is unironed on purpose. Still finished.",
    occasion: "weekend",
    colors: ["grey", "cream", "stone"],
    imageUrl: photo("photo-1515372039744-b8f02a3ae446"),
    slots: ["outerwear", "shirt", "trousers", "shoes"],
    cluster: "Sunday Linen",
    itemIds: ["ow-grey-mac", "sh-cream-oxford", "tr-grey-flannel", "sh-grey-runner"],
  },
  {
    id: "f-evening-silk",
    gender: "female",
    title: "Ink After Dark",
    why: "Black silk and a quiet trouser is enough after dark. Skip the gown.",
    occasion: "night",
    colors: ["black", "charcoal", "grey"],
    imageUrl: photo("photo-1617019114583-affb34d1b3cd"),
    slots: ["shirt", "trousers", "shoes", "accessory"],
    cluster: "Ink After Dark",
    itemIds: ["sh-black-silk", "tr-black-wool", "sh-black-oxford", "ac-black-cardholder"],
  },
  {
    id: "f-chocolate-knit",
    gender: "female",
    title: "Harvest Tweed",
    why: "Warm brown instead of black. The chelsea boot is the only hard edge.",
    occasion: "weekend",
    colors: ["chocolate", "cream", "camel"],
    imageUrl: photo("photo-1475180098004-ca77a66827be"),
    slots: ["knit", "trousers", "shoes", "accessory"],
    cluster: "Harvest Tweed",
    itemIds: ["kn-chocolate-crew", "tr-chocolate-twill", "sh-chocolate-chelsea", "ac-chocolate-belt"],
  },
];

/**
 * Demo-look mapping only (local generate / hooks). Onboarding likes use
 * `data/style-cards.v1.json` — 18 first-party stills under /style-cards/.
 */
export const STYLE_CARDS: StyleCard[] = [
  {
    id: "m-paddock",
    gender: "male",
    cluster: "Paddock Wool",
    label: "Paddock Wool",
    hook: "Camel coat, white tee, a little dirt on the hem.",
    imageUrl: photo("photo-1490111718993-d98654ce6cf7"),
  },
  {
    id: "m-harbor",
    gender: "male",
    cluster: "Harbor Knit",
    label: "Harbor Knit",
    hook: "Cream knit. Weekend that still got dressed.",
    imageUrl: photo("photo-1506634572416-48cdfe530110"),
  },
  {
    id: "m-ink",
    gender: "male",
    cluster: "Ink After Dark",
    label: "Ink After Dark",
    hook: "One dark line. The coat does the talking.",
    imageUrl: photo("photo-1519085360753-af0119f7cbe7"),
  },
  {
    id: "m-linen",
    gender: "male",
    cluster: "Sunday Linen",
    label: "Sunday Linen",
    hook: "Unironed on purpose. Still finished.",
    imageUrl: photo("photo-1488161628813-04466f872be2"),
  },
  {
    id: "m-uptown",
    gender: "male",
    cluster: "Uptown Navy",
    label: "Uptown Navy",
    hook: "City polish. A belt, not a logo.",
    imageUrl: photo("photo-1507679799987-c73779587ccf"),
  },
  {
    id: "m-field",
    gender: "male",
    cluster: "Field & Flannel",
    label: "Field & Flannel",
    hook: "Olive that looks chosen, not camping.",
    imageUrl: photo("photo-1617127365659-c47fa864d8bc"),
  },
  {
    id: "f-paddock",
    gender: "female",
    cluster: "Paddock Cashmere",
    label: "Paddock Cashmere",
    hook: "Tweed energy, tarnish gold, a bag that finishes it.",
    imageUrl: photo("photo-1483985988355-763728e1935b"),
  },
  {
    id: "f-harbor",
    gender: "female",
    cluster: "Harbor Granddaughter",
    label: "Harbor Granddaughter",
    hook: "Salt air, cream knit, nothing precious.",
    imageUrl: photo("photo-1632765937900-a3bbbfa58d46"),
  },
  {
    id: "f-ink",
    gender: "female",
    cluster: "Ink After Dark",
    label: "Ink After Dark",
    hook: "One dark line. The jewelry does the rest.",
    imageUrl: photo("photo-1495385794356-15371f348c31"),
  },
  {
    id: "f-linen",
    gender: "female",
    cluster: "Sunday Linen",
    label: "Sunday Linen",
    hook: "Unironed on purpose. Still finished.",
    imageUrl: photo("photo-1515372039744-b8f02a3ae446"),
  },
  {
    id: "f-uptown",
    gender: "female",
    cluster: "Uptown Saddle",
    label: "Uptown Saddle",
    hook: "Blazer, ballcap energy, a boot that works.",
    imageUrl: photo("photo-1590873802674-55bb8f947bc5"),
  },
  {
    id: "f-harvest",
    gender: "female",
    cluster: "Harvest Tweed",
    label: "Harvest Tweed",
    hook: "Moodier layers. Preppy fall, not costume.",
    imageUrl: photo("photo-1475180098004-ca77a66827be"),
  },
];

export const STYLE_DECK = STYLE_CARDS;

export function stylesForGender(_gender?: GenderId | null): StyleCard[] {
  return STYLE_CARDS.filter((card) => card.gender === FRIEND_GENDER);
}

export function looksForGender(_gender?: GenderId | null): LookTemplate[] {
  return LOOK_TEMPLATES.filter((template) => template.gender === FRIEND_GENDER);
}

export { SEASON_GUIDES as SEASONS } from "./color-analysis";

export const COLOR_SWATCH: Record<ColorId, string> = {
  navy: "#1e2a4a",
  black: "#111111",
  white: "#f4f1ea",
  grey: "#7a7a7a",
  camel: "#c4a574",
  cream: "#e8dcc8",
  chocolate: "#4a3020",
  olive: "#5c6040",
  stone: "#c8bba8",
  sand: "#d4c4a8",
  charcoal: "#3a3a3a",
  red: "#c4282d",
  pink: "#e8919a",
  peach: "#e8b496",
  burgundy: "#722f37",
  blue: "#3b6ea5",
  green: "#2d8a5e",
  /** Fallback chip hex; UI uses closetColorFill conic gradient. */
  multi: "#c45c8a",
};

/** CSS background for closet chips / empty tiles. Multicolor is a rainbow cone, not a single dye. */
export function closetColorFill(id: ColorId): string {
  if (id === "multi") {
    return "conic-gradient(from 200deg,#c4282d,#e8b496,#e4c56a,#2d8a5e,#3b6ea5,#e8919a,#c4282d)";
  }
  return COLOR_SWATCH[id];
}
