'use client';
import {useRef,useState} from 'react';
import {analyzeSignals, SEASON_GUIDES} from '../lib/color-analysis';
type Point={x:number;y:number};
const labels=['skin','hair','eyes'] as const;
export function PhotoSeason({readPhoto,onResult}:{readPhoto:(f:File)=>Promise<string>;onResult:(season:string,summary:string)=>void}){
 const [photo,setPhoto]=useState('');const [points,setPoints]=useState<Partial<Record<typeof labels[number],Point>>>({});const [target,setTarget]=useState<typeof labels[number]>('skin');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const img=useRef<HTMLImageElement>(null);
 function estimate(){try{const el=img.current;if(!el||labels.some(k=>!points[k]))return;const canvas=document.createElement('canvas');canvas.width=el.naturalWidth;canvas.height=el.naturalHeight;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Photo analysis is not supported in this browser.');ctx.drawImage(el,0,0);const sample=(p:Point)=>{const x=Math.min(canvas.width-1,Math.max(0,Math.round(p.x*canvas.width))),y=Math.min(canvas.height-1,Math.max(0,Math.round(p.y*canvas.height)));const radius=Math.max(1,Math.round(canvas.width*.005));const left=Math.max(0,x-radius),top=Math.max(0,y-radius);const d=ctx.getImageData(left,top,Math.min(radius*2+1,canvas.width-left),Math.min(radius*2+1,canvas.height-top)).data;const c={r:0,g:0,b:0};for(let i=0;i<d.length;i+=4){c.r+=d[i];c.g+=d[i+1];c.b+=d[i+2];}const n=d.length/4;return {r:c.r/n,g:c.g/n,b:c.b/n};};const s=sample(points.skin!),h=sample(points.hair!),e=sample(points.eyes!);const lum=(c:typeof s)=>.2126*c.r+.7152*c.g+.0722*c.b;const sat=(c:typeof s)=>{const max=Math.max(c.r,c.g,c.b),min=Math.min(c.r,c.g,c.b);return max?(max-min)/max:0;};if(lum(s)<25||lum(s)>245)throw new Error('That skin sample is too dark or bright. Pick a naturally lit cheek area.');const result=analyzeSignals({warmth:s.r-s.b,yellow:s.r+s.g-2*s.b,skinL:lum(s),hairL:lum(h),eyeL:lum(e),eyeWarmth:e.r-e.b,contrast:Math.abs(lum(s)-lum(h))*.75+Math.abs(lum(s)-lum(e))*.25,chroma:sat(s)*.7+sat(e)*.3},true,s);let name=SEASON_GUIDES.find(g=>g.id===result.season)!.label.replace(/\b\w/g,c=>c.toUpperCase());name=name.replace('True Spring','Warm Spring').replace('True Summer','Cool Summer').replace('True Autumn','Warm Autumn').replace('True Winter','Cool Winter').replace('Dark','Deep');onResult(name,result.summary);setError('');}catch(e){setError((e as Error).message);}}
 return <section className="photo-season"><p>Use a face photo in natural daylight, without filters or strong makeup. Pick a cheek, natural hair, and iris so the estimate samples the right areas.</p><label className="upload-box"><span>{busy?'Opening photo…':photo?'Choose another photo':'Choose a face photo'}</span><input type="file" accept="image/*" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setBusy(true);setError('');try{setPhoto(await readPhoto(f));setPoints({});setTarget('skin');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}/></label>{photo&&<><div className="chips">{labels.map(k=><button key={k} className={'chip '+(target===k?'selected':'')} aria-pressed={target===k} onClick={()=>setTarget(k)}>{points[k]?'✓ ':''}{k==='skin'?'1. Cheek':k==='hair'?'2. Natural hair':'3. Iris'}</button>)}</div><div className="face-sampler" role="group" aria-label="Photo color samples"><img ref={img} src={photo} alt="Your face photo for selecting color samples"/><button className="sample-surface" aria-label={'Select '+target+' color on photo; arrow keys move, Enter selects'} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();const p={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};setPoints(s=>({...s,[target]:p}));setTarget(target==='skin'?'hair':target==='hair'?'eyes':'eyes');}} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter'].includes(e.key))return;e.preventDefault();const p=points[target]||{x:.5,y:.5};if(e.key==='Enter'){setPoints(s=>({...s,[target]:p}));setTarget(target==='skin'?'hair':target==='hair'?'eyes':'eyes');}else setPoints(s=>({...s,[target]:{x:Math.max(0,Math.min(1,p.x+(e.key==='ArrowRight'?.01:e.key==='ArrowLeft'?-.01:0))),y:Math.max(0,Math.min(1,p.y+(e.key==='ArrowDown'?.01:e.key==='ArrowUp'?-.01:0)))}}));}}/>{labels.map(k=>points[k]&&<span key={k} className="sample-marker" style={{left:points[k]!.x*100+'%',top:points[k]!.y*100+'%'}}>{k[0].toUpperCase()}</span>)}</div><button className="primary full" disabled={labels.some(k=>!points[k])} onClick={estimate}>Estimate my season</button></>}{error&&<p role="alert" className="dialog-notice">{error}</p>}<p className="fine-print">A starting estimate, not a definitive color analysis. Lighting and dyed hair can change the result. Your photo stays in this browser and is not saved with your profile.</p></section>;
}
