'use client';
import {ColorSelect} from './color-select';
import {useRef,useState} from 'react';
export type EditablePiece={name:string;role:string;color:string;image?:string};
export function PieceEditor({value,onChange,source,readPhoto,disabled=false}:{value:EditablePiece;onChange:(value:EditablePiece)=>void;source?:string;readPhoto:(f:File)=>Promise<string>;disabled?:boolean}){
 const [reference,setReference]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [candidate,setCandidate]=useState('');
 if(!value.image)return <BeforeCutoutEditor key={value.name+'|'+value.color+'|'+value.role} value={value} onChange={onChange} disabled={disabled}/>;
 return <details className="piece-editor"><summary>Edit details or fix cutout</summary><fieldset disabled={disabled||busy}><label className="field">Name<input value={value.name} maxLength={300} onChange={e=>onChange({...value,name:e.target.value})}/></label><label className="field">Color<ColorSelect value={value.color} onChange={color=>onChange({...value,color})}/></label><label className="field">Category<select value={value.role} onChange={e=>onChange({...value,role:e.target.value})}>{['top','bottom','dress','outerwear','shoes','bag','accessory'].map(role=><option key={role}>{role}</option>)}</select></label><p className="fine-print">Detail edits update your closet label. To change the image too, describe the correction and redo the cutout.</p><label className="field">What should change?<textarea maxLength={600} rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="Only the brown hat on the floor; no dress. Or: keep these boots, but correct them to brown."/></label><label className="field">Optional close-up of this item<input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setBusy(true);setError('');try{setReference(await readPhoto(f));setCandidate('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}/></label>{reference&&<><img className="piece-reference" src={reference} alt="Replacement source photo"/><button className="text-link" onClick={()=>setReference('')}>Use original reference instead</button></>}<button className="secondary full" disabled={!value.name.trim()||!(reference||source||value.image)} onClick={async()=>{setBusy(true);setError('');setCandidate('');try{const r=await fetch('/api/closet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cutout',image:reference||source||value.image,item:{name:value.name,role:value.role,color:value.color},correction:note})});const result=await r.json();if(!r.ok)throw new Error(result.error||'Could not redo this cutout.');setCandidate(result.image);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Redo cutout</button><p className="fine-print">Only this item is regenerated. For a missing or wrong object, a close-up gives GPT a clearer reference.</p></fieldset>{busy&&<p role="status">Preparing this cutout…</p>}{error&&<p role="alert">{error}</p>}{candidate&&<div className="replacement-cutout"><img src={candidate} alt={'New cutout of '+value.name}/><button className="primary" disabled={disabled||busy} onClick={()=>{onChange({...value,image:candidate});setCandidate('');}}>Use this cutout</button><button className="text-link" onClick={()=>setCandidate('')}>Keep previous image</button></div>}</details>;
}

function BeforeCutoutEditor({value,onChange,disabled}:{value:EditablePiece;onChange:(value:EditablePiece)=>void;disabled:boolean}){
 const [draft,setDraft]=useState(value);const panel=useRef<HTMLDetailsElement>(null);
 return <details ref={panel} className="piece-editor"><summary>Edit details</summary><fieldset disabled={disabled}><label className="field">Name<input value={draft.name} maxLength={300} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="field">Color<ColorSelect value={draft.color} onChange={color=>setDraft({...draft,color})}/></label><label className="field">Category<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}>{['top','bottom','dress','outerwear','shoes','bag','accessory'].map(role=><option key={role}>{role}</option>)}</select></label><button className="secondary full" disabled={!draft.name.trim()} onClick={()=>{onChange({...draft,name:draft.name.trim()});if(panel.current)panel.current.open=false;}}>Save</button></fieldset></details>;
}
